version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retaildb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dashboard:
    build: .
    ports:
      - "8050:8050"
    depends_on:
      - db

volumes:
  pgdata: